/*  function calculateStatistics (scores){
    let min = scores[0];
    let max = scores[0];
    let sum = 0;

    for (let score in scores){
        if (score > max){
            max = score;
        }
        else if(score < min){
            min = score;
        }
        sum += score;
    }
    return [min,max,"Hello"];
}

let statistics = calculateStatistics([25,39,78,66,74,80]);

let min = statistics[0];
let max = statistics[1];
let msg = statistics[2]; // Contains hello */
//let mytuple = [10,"Hello"];
var myTuple = [];
myTuple[0] = 120;
myTuple[1] = 234;
console.log(myTuple);
var detailsTuple = [101, "Lasya", 102, "Meghana", false, null, undefined, ["loukhya", "Advith"], {}]; //create a  tuple
/*
console.log(detailsTuple[0]);
console.log(detailsTuple[1]);
 */
detailsTuple.forEach(function (value) {
    console.log(value);
});
var Tuple = [10, "Hello", "Welcome To", "typeScript"];
console.log("Items before push " + Tuple.length);
Tuple.push("pushing Value");
console.log("Items after push " + Tuple.length);
console.log("Items before pop " + Tuple.length);
console.log(Tuple.pop() + " popped from the tuple");
console.log("Items after pop " + Tuple.length);
var a = [101, "hello", [102, "rama"]];
var b = a[0], c = a[1], d = a[2];
console.log(b);
console.log(c);
console.log(d);
//Generated by typescript 1.8.10
var t1 = [10, "hello"];
var t2 = t1[0];
var t3 = t1[1];
console.log(t2);
console.log(t3);
